   var addvcd_data = [
	   {
	"id":1,
	"text":"广西壮族自治区",
	"children":[{
		"id":11,
		"text":"Photos",
		"state":"closed",
		"children":[{
			"id":111,
			"text":"Friend"
		},{
			"id":112,
			"text":"Wife"
		},{
			"id":113,
			"text":"Company"
		}]
	}]
},
	   {
		   "id":1,
		   "text":"广西壮族自治区",
		   "children":[{
			   "id":11,
			   "text":"Photos",
			   "state":"closed",
			   "children":[{
				   "id":111,
				   "text":"Friend"
			   },{
				   "id":112,
				   "text":"Wife"
			   },{
				   "id":113,
				   "text":"Company"
			   }]
		   }]
	   },
   ];